/**
 * Sistem Informasi Akademik System Index v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 13:50:26
 *
 * Domains: 1 | Classes: 4 | Relationships: 2
 * Complete type-safe exports for all system entities
 */

export * from './manajemenAkademik';
