/**
 * Dosen Class extends Person - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: Dosen (DSN) | Domain: Manajemen Civitas Akademika | State Machine | Inheritance
 * Merepresentasikan seorang dosen pengajar.
 */

import { IDosen } from './idosen';
import { Person } from './person';

export class Dosen extends Person implements IDosen {
  public nip?: string;
  public status?: string = 'Aktif Mengajar';
  public state: 'Aktif Mengajar' | 'Cuti Akademik' | 'Pensiun' = 'Aktif Mengajar';

  constructor(id: string) {
    super(id);
  }

  // State Machine Methods
  public ajukancuti(durasicuti: number): boolean {
    if (this.state === 'Aktif Mengajar') {
      this.status = 'Cuti Akademik';
      console.log(`Dosen ${this.nip} mengajukan cuti selama ${durasicuti} bulan.`);
      this.state = 'Cuti Akademik';
      return true;
    }
    return false;
  }

  public selesaicuti(tanggalkembali: Date): boolean {
    if (this.state === 'Cuti Akademik') {
      this.status = 'Aktif Mengajar';
      console.log(`Dosen ${this.nip} kembali mengajar pada ${tanggalkembali}.`);
      this.state = 'Aktif Mengajar';
      return true;
    }
    return false;
  }

  public memasukipensiun(tanggalpensiun: Date): boolean {
    if (this.state === 'Aktif Mengajar') {
      this.status = 'Pensiun';
      console.log(`Dosen ${this.nip} pensiun per ${tanggalpensiun}.`);
      this.state = 'Pensiun';
      return true;
    }
    return false;
  }

}
