/**
 * Dosen Interface - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: Dosen (DSN) | Domain: Manajemen Civitas Akademika | State Machine: Yes
 * Merepresentasikan seorang dosen pengajar.
 */

import { IPerson } from './iperson';

export interface IDosen extends IPerson {
  nip?: string;
  status?: string;
  state: 'Aktif Mengajar' | 'Cuti Akademik' | 'Pensiun';
}
