/**
 * JadwalAjar Interface - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: JadwalAjar (JA) | Domain: Manajemen Civitas Akademika | State Machine: No
 * Association class for relationship R2
 */

export interface IJadwalajar {
  jadwalId: string;
  dosenId?: string;
  matakuliahKodemk?: string;
  tahunakademik?: string;
}
