/**
 * KRS Interface - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: KRS (KRS) | Domain: Manajemen Civitas Akademika | State Machine: No
 * Association class for relationship R1
 */

export interface IKrs {
  krsId: string;
  mahasiswaId?: string;
  matakuliahKodemk?: string;
  semester?: string;
  nilai?: string;
}
