/**
 * Mahasiswa Interface - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: Mahasiswa (MHS) | Domain: Manajemen Civitas Akademika | State Machine: Yes
 * Merepresentasikan seorang mahasiswa yang terdaftar.
 */

import { IPerson } from './iperson';

export interface IMahasiswa extends IPerson {
  nim?: string;
  status?: string;
  state: 'Aktif' | 'Cuti' | 'Lulus';
}
