/**
 * Manajemen Civitas Akademika Domain Index - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Domain: Manajemen Civitas Akademika (MCA) | Classes: 4 | Relationships: 2
 * Auto-generated exports for all domain entities
 */

export { IPerson } from './iperson';
export { Person } from './person';
export { IMahasiswa } from './imahasiswa';
export { Mahasiswa } from './mahasiswa';
export { IDosen } from './idosen';
export { Dosen } from './dosen';
export { IMatakuliah } from './imatakuliah';
export { Matakuliah } from './matakuliah';
export { IKrs } from './ikrs';
export { Krs } from './krs';
export { IJadwalajar } from './ijadwalajar';
export { Jadwalajar } from './jadwalajar';
