/**
 * Person Interface - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: Person (PRS) | Domain: Manajemen Civitas Akademika | State Machine: No
 * Superclass untuk semua individu dalam sistem.
 */

export interface IPerson {
  id: string;
  nama?: string;
  email?: string;
}
