/**
 * JadwalAjar Class - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: JadwalAjar (JA) | Domain: Manajemen Civitas Akademika
 * Association class for relationship R2
 */

import { IJadwalajar } from './ijadwalajar';

export class Jadwalajar implements IJadwalajar {
  public jadwalId: string;
  public dosenId?: string;
  public matakuliahKodemk?: string;
  public tahunakademik?: string;

  constructor(jadwalId: string) {
    this.jadwalId = jadwalId;
  }
}
