/**
 * Mahasiswa Class extends Person - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: Mahasiswa (MHS) | Domain: Manajemen Civitas Akademika | State Machine | Inheritance
 * Merepresentasikan seorang mahasiswa yang terdaftar.
 */

import { IMahasiswa } from './imahasiswa';
import { Person } from './person';

export class Mahasiswa extends Person implements IMahasiswa {
  public nim?: string;
  public status?: string = 'Aktif';
  public state: 'Aktif' | 'Cuti' | 'Lulus' = 'Aktif';

  constructor(id: string) {
    super(id);
  }

  // State Machine Methods
  public ambilcuti(alasan: string): boolean {
    if (this.state === 'Aktif') {
      this.status = 'Cuti';
      console.log(`Mahasiswa ${this.nim} mengajukan cuti dengan alasan: ${alasan}.`);
      this.state = 'Cuti';
      return true;
    }
    return false;
  }

  public aktifkankembali(tanggalaktif: Date): boolean {
    if (this.state === 'Cuti') {
      this.status = 'Aktif';
      console.log(`Mahasiswa ${this.nim} aktif kembali per ${tanggalaktif}.`);
      this.state = 'Aktif';
      return true;
    }
    return false;
  }

  public dinyatakanlulus(tanggallulus: Date): boolean {
    if (this.state === 'Aktif') {
      this.status = 'Lulus';
      console.log(`Mahasiswa ${this.nim} telah lulus pada ${tanggallulus}.`);
      this.state = 'Lulus';
      return true;
    }
    return false;
  }

}
