/**
 * MataKuliah Class - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: MataKuliah (MK) | Domain: Manajemen Civitas Akademika
 * Kelas pasif yang merepresentasikan mata kuliah.
 */

import { IMatakuliah } from './imatakuliah';

export class Matakuliah implements IMatakuliah {
  public kodemk: string;
  public namamk?: string;
  public sks?: number;

  constructor(kodemk: string) {
    this.kodemk = kodemk;
  }
}
