/**
 * Abstract Person Class - SistemAkademik v1.0.0
 * Generated by xTUML TypeScript Compiler v1.1.0 on 2025-10-17 05:55:57
 *
 * Entity: Person (PRS) | Domain: Manajemen Civitas Akademika
 * Superclass untuk semua individu dalam sistem.
 */

import { IPerson } from './iperson';

export abstract class Person implements IPerson {
  public id: string;
  public nama?: string;
  public email?: string;

  constructor(id: string) {
    this.id = id;
  }
}
